"""Repository ports (Protocols).

Each repository speaks in **domain entities**, never ORM rows. Concrete
implementations live in the infrastructure layer and are bound to a session by
the Unit of Work. The application layer knows only these interfaces.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from playnext.core.money import Money
from playnext.domain.enums import OrderStatus, WalletTxnType
from playnext.domain.models import (
    Category,
    Order,
    Product,
    PromoCode,
    User,
    WalletTransaction,
)


class UserRepository(Protocol):
    async def get(self, user_id: int) -> User | None: ...
    async def get_or_create(
        self, user_id: int, *, username: str | None, first_name: str
    ) -> User: ...
    async def set_blocked(self, user_id: int, blocked: bool) -> None: ...
    async def all_ids(self) -> list[int]: ...
    async def count(self) -> int: ...
    async def list_recent(self, *, limit: int, offset: int) -> list[User]: ...


class CategoryRepository(Protocol):
    async def get(self, category_id: int) -> Category | None: ...
    async def list_active(self) -> list[Category]: ...
    async def list_all(self) -> list[Category]: ...
    async def create(self, *, title: str, sort_order: int) -> Category: ...
    async def update(
        self,
        category_id: int,
        *,
        title: str | None = None,
        is_active: bool | None = None,
    ) -> None: ...
    async def delete(self, category_id: int) -> None: ...


class ProductRepository(Protocol):
    async def get(self, product_id: int) -> Product | None: ...
    async def get_many(self, product_ids: list[int]) -> list[Product]: ...
    async def list_by_category(
        self, category_id: int, *, limit: int, offset: int, active_only: bool = True
    ) -> tuple[list[Product], int]: ...
    async def search(self, query: str, *, limit: int, offset: int) -> tuple[list[Product], int]: ...
    async def list_newest(self, *, limit: int) -> list[Product]: ...
    async def list_featured(self, *, limit: int) -> list[Product]: ...
    async def list_by_variant_group(self, group: str) -> list[Product]: ...
    async def list_all(self, *, limit: int, offset: int) -> tuple[list[Product], int]: ...
    async def create(
        self,
        *,
        category_id: int,
        title: str,
        description: str,
        price: Money,
        image_file_id: str | None,
        is_featured: bool = False,
        variant_group: str | None = None,
    ) -> Product: ...
    async def update(
        self,
        product_id: int,
        *,
        title: str | None = None,
        description: str | None = None,
        price: Money | None = None,
        image_file_id: str | None = None,
        is_active: bool | None = None,
    ) -> None: ...
    async def delete(self, product_id: int) -> None: ...
    async def count_active(self) -> int: ...


class StockKeyRepository(Protocol):
    async def add_keys(self, product_id: int, secrets: list[str]) -> int: ...
    async def count_available(self, product_id: int) -> int: ...
    async def total_available(self) -> int: ...
    async def consume(self, product_id: int, quantity: int, *, order_id: int) -> list[str]:
        """Atomically claim `quantity` available keys, mark them sold, return secrets.

        Must lock rows (SELECT ... FOR UPDATE SKIP LOCKED) so concurrent
        checkouts can never sell the same key twice.
        """
        ...

    async def has_sold(self, product_id: int) -> bool:
        """True if the product has ever had a key delivered (guards hard delete)."""
        ...

    async def has_sold_in_category(self, category_id: int) -> bool:
        """True if any product in the category has ever had a key delivered."""
        ...


class CartRepository(Protocol):
    async def lines(self, user_id: int) -> list[tuple[int, int]]:
        """Return [(product_id, quantity)] for the user's cart."""
        ...

    async def set_quantity(self, user_id: int, product_id: int, quantity: int) -> None: ...
    async def remove(self, user_id: int, product_id: int) -> None: ...
    async def clear(self, user_id: int) -> None: ...


class PromoRepository(Protocol):
    async def get(self, code: str) -> PromoCode | None: ...
    async def list_all(self) -> list[PromoCode]: ...
    async def list_active(self) -> list[PromoCode]:
        """Codes that are active, not expired and not exhausted (see
        PromoCode.is_available) — independent of any particular cart."""
        ...

    async def create(self, promo: PromoCode) -> None: ...
    async def increment_uses(self, code: str) -> None: ...
    async def set_active(self, code: str, active: bool) -> None: ...


class OrderRepository(Protocol):
    async def create(self, order: Order) -> Order: ...
    async def get(self, order_id: int) -> Order | None: ...
    async def list_by_user(
        self, user_id: int, *, limit: int, offset: int
    ) -> tuple[list[Order], int]: ...
    async def count_by_user(self, user_id: int) -> int: ...
    async def total_spent_by_user(self, user_id: int) -> Money: ...
    async def list_recent(self, *, limit: int, offset: int) -> tuple[list[Order], int]: ...
    async def set_status(self, order_id: int, status: OrderStatus) -> None: ...
    async def count_all(self) -> int: ...
    async def revenue_total(self) -> Money: ...
    async def top_products(self, *, limit: int) -> list[tuple[int, int, Money]]:
        """Return [(product_id, sold_units, revenue)] ordered by units sold desc."""
        ...

    async def sold_count(self, product_id: int) -> int:
        """Total units of this product ever delivered (fulfilled orders)."""
        ...


class WalletRepository(Protocol):
    async def get_balance(self, user_id: int) -> Money: ...
    async def apply(
        self,
        user_id: int,
        *,
        type: WalletTxnType,
        amount: Money,
        order_id: int | None = None,
        note: str | None = None,
    ) -> WalletTransaction:
        """Atomically adjust balance (locking the user row) and append a ledger entry."""
        ...

    async def list_transactions(
        self, user_id: int, *, limit: int, offset: int
    ) -> tuple[list[WalletTransaction], int]: ...


class PaymentRepository(Protocol):
    async def create(self, *, user_id: int, provider: str, amount: Money) -> int: ...
    async def attach_provider(
        self, payment_id: int, *, provider_payment_id: str, confirmation_url: str | None
    ) -> None: ...
    async def get(self, payment_id: int) -> PaymentRow | None: ...
    async def mark_succeeded(self, payment_id: int) -> bool:
        """Transition PENDING -> SUCCEEDED. Returns True only on the first transition
        (idempotency guard against double-crediting)."""
        ...

    async def set_status_by_id(self, payment_id: int, status: str) -> None: ...
    async def list_recent(self, *, limit: int, offset: int) -> tuple[Sequence[PaymentRow], int]: ...


class PaymentRow(Protocol):
    """Minimal read shape for a stored payment (avoids leaking ORM types).

    Declared as read-only properties (not plain attributes): this is a value
    read out of storage, never written back through the port, and read-only
    Protocol members are satisfied by any matching attribute — mutable or
    frozen — whereas plain mutable ones require invariant, settable fields.
    """

    @property
    def id(self) -> int: ...
    @property
    def user_id(self) -> int: ...
    @property
    def provider(self) -> str: ...
    @property
    def provider_payment_id(self) -> str | None: ...
    @property
    def amount(self) -> Money: ...
    @property
    def status(self) -> str: ...
    @property
    def confirmation_url(self) -> str | None: ...


class FavoriteRepository(Protocol):
    async def is_favorite(self, user_id: int, product_id: int) -> bool: ...
    async def add(self, user_id: int, product_id: int) -> None: ...
    async def remove(self, user_id: int, product_id: int) -> None: ...
    async def list_products(
        self, user_id: int, *, limit: int, offset: int
    ) -> tuple[list[Product], int]: ...


class RecentlyViewedRepository(Protocol):
    async def record(self, user_id: int, product_id: int) -> None:
        """Upsert: (user_id, product_id) is unique, viewing again just bumps the time."""
        ...

    async def list_products(self, user_id: int, *, limit: int) -> list[Product]:
        """Most recently viewed first."""
        ...
